config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'events/index', to: 'events#index'
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :events
  resources :invitations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: :user_id, class_name: :User, required: false
  has_many :invitations
  has_many :users, through: :invitations

  scope :past_events, -> { where('date < ?', Time.now) }
  scope :upcoming_events, -> { where('date > ?', Time.now) }

  def self.find_upcoming_events
    upcoming_events.order('created_at DESC').pluck(:location, :date, :name, :description)
  end

  def self.find_past_events
    past_events.order('created_at DESC').pluck(:location, :date, :name, :description)
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attended_event, foreign_key: :event_id, class_name: :Event, required: false
  belongs_to :attendee, foreign_key: :user_id, class_name: :User, required: false
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { in: 3..12 }
  validates :email, presence: true, uniqueness: true
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :user_signed_in?

  # GET /events or /events/index
  def index
    @past_events = Event.past_events
    @upcoming_events = Event.upcoming_events
  end

  # GET /events/1 or /events/1.json
  def show
    @invites = Invitation.where(event_id: params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:location, :date, :name, :description)
  end

  def user_signed_in?
    if current_user
      true
    else
      redirect_to login_path
    end
  end

  def current_user
    User.find_by(id: cookies[:user_id])
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :user_signed_in?

  def index
    @invitations = Invitation.all
  end

  def new
    @invitation = Invitation.new
    @event = params[:event_id]
    @users = User.all
  end

  def create
    email = invitation_params[:email]
    @user = User.where(email: email).pluck(:id)
    @invitation = Invitation.new(user_id: @user[0], event_id: params[:event_id])
    if @invitation.save
      redirect_to root_path
    else
      render 'new', event_id: params[:event_id]
    end
  end

  def destroy
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def user_signed_in?
    if current_user
      true
    else
      redirect_to login_path
    end
  end

  def current_user
    User.find_by(id: cookies[:user_id])
  end

  def invitation_params
    params.permit(:id, :email, :authenticity_token, :commit, :event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(username: params[:username])
    if @user
      cookies[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def destroy
    cookies[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in?, only: %i[index show]
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      cookies[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @prev_events = current_user.events.upcoming_events
    @upcoming_events = current_user.events.past_events
  end

  private

  def user_params
    params.require(:user).permit(:email, :username)
  end

  def user_signed_in?
    if current_user
      true
    else
      redirect_to login_path
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def current_user
    User.find_by(id: cookies[:user_id])
  end

  def authenticate_user
    redirect_to login_path if current_user.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def same_as_event_creator(event_user_id)
    cookies[:user_id].to_i.eql?(event_user_id.to_i) ? true : false
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', root_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<%= link_to 'New Event', new_event_path %><br>
<%= link_to 'My Events', user_path(cookies[:user_id]) %>

<br>

<br>

<div class="col">
    <h2>Past Events</h2>
    <p>
      <table>
        <thead>
          <tr>
            <th>Location</th>
            <th>Date</th>
            <th>Name</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @past_events.each do |event| %>
            <tr>
              <td><%= event.location %></td>
              <td><%= event.date %></td>
              <td><%= event.name %></td>
              <td><%= event.description %></td>
              <td><%= link_to 'Show', event %></td>
              <% if same_as_event_creator(event.user_id)%>
                <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <td><%= link_to 'Edit', edit_event_path(event) %></td>
                <td><%= link_to 'Invite', new_invitation_path(:event_id => event.id) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </p>
</div>

<br>

<div class="col">
  <h2>Upcoming Events</h2>
  <p>
    <table>
      <thead>
        <tr>
          <th>Location</th>
          <th>Date</th>
          <th>Name</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @upcoming_events.each do |event| %>
          <tr>
            <td><%= event.location %></td>
            <td><%= event.date %></td>
            <td><%= event.name %></td>
            <td><%= event.description %></td>
            <td><%= link_to 'Show', event %></td>
            <% if same_as_event_creator(event.user_id)%>
              <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to 'Edit', edit_event_path(event) %></td>
              <td><%= link_to 'Invite', new_invitation_path(:event_id => event.id) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </p>
</div>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', root_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Event</h1>

<p>
  <h3>Creator</h3>
  
  <p>
    <strong>Username:</strong>
    <%= @event.creator.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @event.creator.email %>
  </p>
</p>

<br />

<p>
  <h3>Event Details</h3>

  <p>
    <strong>Location:</strong>
    <%= @event.location %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @event.date %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>
</p>

<br />

<h3>Invitees</h3>

<p>
  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
      </tr>
    </thead>

    <tbody>
      <% @invites.each do |invite| %>
        <tr>
          <td><%= invite.attendee.username %></td>
          <td><%= invite.attendee.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<br />

<% if same_as_event_creator(@event.user_id) %>
  <%= link_to 'Invite', new_invitation_path(:event_id => @event.id) %> |
  <%= link_to 'Edit', edit_event_path(@event) %>
<% end %>

<br />

<%= link_to 'Back', root_path %>

app/views/invitations/new.html.erb
<h1> Invite </h1>

<%= form_with model: @invitation, method: :post do |f| %>
  Enter a user's email: <%= text_field_tag :email %>
  <%= hidden_field_tag 'event_id', @event  %>
   <%= f.submit 'Invite' %>
<% end %>   
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/users/new.html.erb
<h1>Create User</h1>

<%= form_with model: @user, method: :put do |f| %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  
  <%= f.label :email %>
  <%= f.email_field :email, placeholder: "Enter your email address", required: 'required', class:"placeholder" %>
  <br>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Enter your username", required: 'required', class:"placeholder" %>
  <br>
  <%= f.submit 'Save' %>
<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= form_with model: @user, method: :post do |f| %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  
  <%= f.label :email %>
  <%= f.email_field :email, placeholder: "Enter your email address", required: 'required', class:"placeholder" %>
  <br>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Enter your username", required: 'required', class:"placeholder" %>
  <br>
  <%= f.submit 'Save' %>
<% end %>

app/views/users/show.html.erb
<h1>User</h1>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'New Event', new_event_path %>

<br />

<br />

<h2>My Events</h2>

<h3>Past Events</h3>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Date</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prev_events.each do |event| %>
      <tr>
        <td><%= event.location %></td>
        <td><%= event.date %></td>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Invite', new_invitation_path(:event_id => event.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3>Upcoming Events</h3>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Date</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upcoming_events.each do |event| %>
      <tr>
        <td><%= event.location %></td>
        <td><%= event.date %></td>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Invite', new_invitation_path(:event_id => event.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', root_path %>